INSERT INTO CATEGORY VALUES (0, 'Category 0');				 
INSERT INTO CATEGORY VALUES (1, 'Category 1');
INSERT INTO CATEGORY VALUES (2, 'Category 2');
INSERT INTO CATEGORY VALUES (3, 'Category 3');			

INSERT INTO TAG VALUES (0, 'Tags 0');
INSERT INTO TAG VALUES (1, 'Tags 1');
INSERT INTO TAG VALUES (2, 'Tags 2');
INSERT INTO TAG VALUES (3, 'Tags 3');	 